export const SPOTIFY_CLIENT_ID_KEY: string = "SPOTIFY_CLIENT_ID";
export const SPOTIFY_CLIENT_SECRET_KEY: string = "SPOTIFY_SECRET_ID";
export const SPOTIFY_REFRESH_TOKEN_KEY: string = "SPOTIFY_REFRESH_TOKEN";
export const SITE_URL_KEY: string = "NEXT_PUBLIC_SITE_URL";
